version: '3.1'

services:

  db:
    image: mariadb
    environment:
      MARIADB_DATABASE: gildedrose
      MARIADB_ROOT_PASSWORD: pass

  flask:
    build: .
    command: sh -c './wait-for db:3306 -- flask init-db && flask run --host=0.0.0.0 --port=5000'
    ports:
      - "5000:5000"
    depends_on:
      - "db"